const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#00C2FF",
    background: "#F0F4FF",
    foreground: "#0A0E1A",
    card: "#FFFFFF",
    cardForeground: "#0A0E1A",
    primary: "#0057FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EEFF",
    secondaryForeground: "#1A2340",
    muted: "#E8EEFF",
    mutedForeground: "#6B7A9A",
    accent: "#00C2FF",
    accentForeground: "#0A0E1A",
    destructive: "#FF3B5C",
    destructiveForeground: "#FFFFFF",
    border: "#D8E0FF",
    input: "#D8E0FF",
    success: "#00C896",
    successForeground: "#FFFFFF",
    warning: "#FF9500",
    warningForeground: "#FFFFFF",
    info: "#00C2FF",
  },
  dark: {
    text: "#E8EEFF",
    tint: "#00C2FF",
    background: "#070C1A",
    foreground: "#E8EEFF",
    card: "#0E1629",
    cardForeground: "#E8EEFF",
    primary: "#0066FF",
    primaryForeground: "#FFFFFF",
    secondary: "#131F3A",
    secondaryForeground: "#B8C4E0",
    muted: "#131F3A",
    mutedForeground: "#6B7A9A",
    accent: "#00C2FF",
    accentForeground: "#070C1A",
    destructive: "#FF3B5C",
    destructiveForeground: "#FFFFFF",
    border: "#1A2845",
    input: "#1A2845",
    success: "#00C896",
    successForeground: "#070C1A",
    warning: "#FF9500",
    warningForeground: "#070C1A",
    info: "#00C2FF",
  },
  radius: 14,
};

export default colors;
