import type { ScanResult, Signal, Verdict } from "@/context/ScanContext";

function seededRand(seed: number) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return Math.abs(s) / 0x80000000;
  };
}

function hashStr(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

const TEXT_SIGNALS = [
  {
    label: "Linguistic Consistency",
    desc: "Evaluates natural language patterns and writing style coherence.",
  },
  {
    label: "Factual Grounding",
    desc: "Cross-references claims against known reliable sources.",
  },
  {
    label: "Emotional Manipulation",
    desc: "Detects use of fear, outrage, or urgency to bypass critical thinking.",
  },
  {
    label: "Source Attribution",
    desc: "Checks for verifiable, traceable citations and quotes.",
  },
  {
    label: "AI Generation Likelihood",
    desc: "Probability that this text was generated by an LLM.",
  },
];

const IMAGE_SIGNALS = [
  {
    label: "Facial Coherence",
    desc: "Examines facial symmetry, skin texture, and hairline artifacts.",
  },
  {
    label: "Metadata Integrity",
    desc: "Checks EXIF data for signs of editing or manipulation.",
  },
  {
    label: "GAN Fingerprint",
    desc: "Detects patterns left by generative adversarial networks.",
  },
  {
    label: "Compression Artifacts",
    desc: "Analyzes JPEG/PNG artifacts for signs of compositing.",
  },
  {
    label: "Lighting Consistency",
    desc: "Verifies that light sources and shadows match throughout the image.",
  },
];

const URL_SIGNALS = [
  {
    label: "Domain Reputation",
    desc: "Checks domain age, registration, and trust score.",
  },
  {
    label: "SSL Certificate",
    desc: "Validates HTTPS configuration and certificate authenticity.",
  },
  {
    label: "Content Bias Score",
    desc: "Detects one-sided reporting or propaganda-style framing.",
  },
  {
    label: "Clickbait Index",
    desc: "Analyzes headline vs. article body for sensationalism.",
  },
  {
    label: "Phishing Indicators",
    desc: "Looks for redirects, lookalike domains, and suspicious scripts.",
  },
];

const TEXT_SUMMARIES: Record<Verdict, string[]> = {
  authentic: [
    "This text shows consistent linguistic patterns and verifiable factual claims. No AI generation signatures detected.",
    "The content reads as genuine human-authored writing with traceable references and grounded assertions.",
  ],
  suspicious: [
    "Several claims lack verifiable sources and the language shows mild emotional amplification. Proceed with caution.",
    "Mixed signals: mostly coherent writing, but some sections contain unverifiable assertions and unusual phrasing.",
  ],
  "likely-fake": [
    "High probability of AI-generated or manipulated content. Emotional manipulation tactics and unsourced claims detected.",
    "This text exhibits strong indicators of synthetic generation and intentional misinformation. Do not share.",
  ],
};

const IMAGE_SUMMARIES: Record<Verdict, string[]> = {
  authentic: [
    "No deepfake or manipulation artifacts found. Metadata and visual coherence appear consistent with a real photograph.",
    "Image passes all visual integrity checks. Lighting, shadows, and facial details are consistent throughout.",
  ],
  suspicious: [
    "Minor artifacts detected around facial regions. Could be heavy post-processing or mild AI enhancement.",
    "Some compression inconsistencies found. Image may have been edited, though no clear deepfake signature.",
  ],
  "likely-fake": [
    "Strong GAN fingerprint detected. Facial coherence and background textures show classic deepfake markers.",
    "Multiple manipulation signals triggered. This image is highly likely to be synthetic or heavily altered.",
  ],
};

const URL_SUMMARIES: Record<Verdict, string[]> = {
  authentic: [
    "Domain has strong reputation with consistent SSL and low bias indicators. Content appears reliable.",
    "This URL passes all reputation and content integrity checks. Safe to visit and share.",
  ],
  suspicious: [
    "Domain is relatively new and content shows moderate bias framing. Verify information via independent sources.",
    "Some clickbait headline patterns detected. Core content may be real, but presentation is misleading.",
  ],
  "likely-fake": [
    "Domain shows phishing indicators and content is flagged for extreme bias. High risk of misinformation.",
    "This URL has multiple red flags: lookalike domain, no valid SSL, and heavily manipulative content framing.",
  ],
};

export function generateDummyResult(
  type: "text" | "image" | "url",
  input: string
): Omit<ScanResult, "id" | "scannedAt"> {
  const rand = seededRand(hashStr(input + type));

  const rawScore = rand();
  let verdict: Verdict;
  let confidence: number;

  if (rawScore < 0.35) {
    verdict = "likely-fake";
    confidence = Math.round(72 + rand() * 22);
  } else if (rawScore < 0.6) {
    verdict = "suspicious";
    confidence = Math.round(55 + rand() * 30);
  } else {
    verdict = "authentic";
    confidence = Math.round(78 + rand() * 20);
  }

  const signalDefs =
    type === "text"
      ? TEXT_SIGNALS
      : type === "image"
        ? IMAGE_SIGNALS
        : URL_SIGNALS;

  const signals: Signal[] = signalDefs.map((def) => {
    const base = rand();
    let score: number;
    let flagged: boolean;

    if (verdict === "authentic") {
      score = Math.round(70 + base * 28);
      flagged = score < 78;
    } else if (verdict === "suspicious") {
      score = Math.round(40 + base * 45);
      flagged = score < 65;
    } else {
      score = Math.round(15 + base * 45);
      flagged = score < 60;
    }

    return {
      label: def.label,
      score,
      description: def.desc,
      flagged,
    };
  });

  const summaryArr =
    type === "text"
      ? TEXT_SUMMARIES[verdict]
      : type === "image"
        ? IMAGE_SUMMARIES[verdict]
        : URL_SUMMARIES[verdict];

  const summaryIdx = Math.floor(rand() * summaryArr.length);
  const summary = summaryArr[summaryIdx];

  return { type, input, verdict, confidence, signals, summary };
}
